project:
  type: website
  output-dir: docs/

brand: _brand.yml

website:
  title: "Documentation"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - text: "About"
        href: about/index.qmd
      - text: "How-to"
        href: howto/index.qmd
      - text: "Tutorials"
        href: tutorials/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      # - about.qmd
      # - getstarted.qmd
      # - documentation.qmd
      # - community.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
