---
title: "About"
---

## Overview



## History of BRaVe

The first version of BRaVe, a fully static desktop-based version, was launched in 2014 and has seen continued use since then. More recently a mobile version, internally referred to as BRaVe 2, was piloted in Somalia and a number of countries. In August 2025, development began on BRaVe 3, a comprehensive rearchitecturing and rebuild of the system, replacing both version 2 and 3, with a subsequent launch in 2026. The first open source release of BRaVE was in June 2026.

## Feature Roadmap

The feature roadmap for 2026 and 2027 is currently in development.

## License

BRaVe 3 is released under the open-source [GNU Affero General Public License version 3](https://opensource.org/license/agpl-3-0).

## Contributing

Bug reports and feedback on the tool are welcome. Feel free to fork the project or sumbit pull requests for the code on [Github](https://github.com/bravesystem).

## Useful Links

- [BRaVe landing page](https://brave.iom.int/)
- [BRaVe documentation portal](https://brave.iom.int/)
- [BRaVe Hosted service (testing)](https://testportal.brave.iom.int/)
- [BRaVe Hosted service (production)](https://portal.brave.iom.int/)
- [BRaVe code on Github](https://github.com/bravesystem)
- [IOM's IDP Registration Community of Practice(internal)](https://iomint.sharepoint.com/teams/Registration)

Still haven't found what you're looking for? Contact [IDPRegistrationSupport@iom.int](mailto://IDPRegistrationSupport@iom.int).